name: Build Ringsce

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-linux-arm64:
    name: Build for Linux ARM64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Free Pascal and Dependencies
        run: |
          sudo apt update
          sudo apt install -y fpc lazarus build-essential bison flex automake autoconf git clang

      - name: Show LLVM Info
        run: make llvm-info

      - name: Build Ringsce
        run: make all

      - name: Package Ringsce Binary
        run: |
          mkdir -p release/linux-arm64
          cp kayte-lang/projects/kayte release/linux-arm64/
          cp ekron-realms/tools/toolkit release/linux-arm64/
          tar -czvf ringsce-linux-arm64.tar.gz -C release/linux-arm64 .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ringsce-linux-arm64
          path: ringsce-linux-arm64.tar.gz

  build-macos-arm64:
    name: Build for macOS ARM64
    runs-on: macos-14

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Free Pascal
        run: brew install fpc lazarus

      - name: Show LLVM Info
        run: make llvm-info

      - name: Build Ringsce
        run: make all

      - name: Package Ringsce Binary
        run: |
          mkdir -p release/macos-arm64
          cp kayte-lang/projects/kayte release/macos-arm64/
          cp ekron-realms/tools/toolkit release/macos-arm64/
          tar -czvf ringsce-macos-arm64.tar.gz -C release/macos-arm64 .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ringsce-macos-arm64
          path: ringsce-macos-arm64.tar.gz

  build-rpi3:
    name: Build for Raspberry Pi 3 (ARMv7)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Free Pascal
        run: |
          sudo apt update
          sudo apt install -y fpc lazarus

      - name: Build for Raspberry Pi 3
        run: make all FLAGS="-Tlinux -Parm -O2"

      - name: Package Ringsce Binary
        run: |
          mkdir -p release/rpi3
          cp kayte-lang/projects/kayte release/rpi3/
          cp ekron-realms/tools/toolkit release/rpi3/
          tar -czvf ringsce-rpi3.tar.gz -C release/rpi3 .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ringsce-rpi3
          path: ringsce-rpi3.tar.gz

  build-odroid-c2:
    name: Build for Odroid C2 (ARM64)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Free Pascal
        run: |
          sudo apt update
          sudo apt install -y fpc lazarus

      - name: Build for Odroid C2
        run: make all FLAGS="-Tlinux -Paarch64 -O2"

      - name: Package Ringsce Binary
        run: |
          mkdir -p release/odroid-c2
          cp kayte-lang/projects/kayte release/odroid-c2/
          cp ekron-realms/tools/toolkit release/odroid-c2/
          tar -czvf ringsce-odroid-c2.tar.gz -C release/odroid-c2 .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ringsce-odroid-c2
          path: ringsce-odroid-c2.tar.gz
